# Template type. The valid values are TF, CFT, K8S
# template_type: CFT
# template_type: K8S
template_type: TF

# TF version
# terraform_version: 0.11
# terraform_version: 0.13
terraform_version: 0.12

template_parameters:
   variable_files:
   - './TF/rich-value-types/network/smvariables.tfvars'
   variables:
   - network_config: test
     
tags:
- Org:Engineering
- Team:Shift_Left
- Env:Dev
